name: Development Environment Deploy Process

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Docker Image Build Process
    environment: development
    uses: QuranSunnah/deployment-tools/.github/workflows/development.yaml@main
    with:
      ENVIRONMENT: developmen
      TAG: ${{ github.sha }}
    secrets:
      HOST: ${{ secrets.HOST }}
      USERNAME: ${{ secrets.USERNAME }}
   

    
    